--- 
new_sample: 
setup: default
master-directory: $EPHEMERAL
ref-genome: 
  name: GCF_000002305.2_EquCab2.0_genomic   # or EquCab3
  rename: EquCab2

mapping: 
  aligner: bwa
    - mem
ancestry: true
oral-comparison: true
