--- 
new_sample: xxx
directory: default

mapping: 
 - yes
 - horse
xmas-fifth-day: 
 calling-birds: four
 french-hens: 1
 golden-rings: 5
 partridges: 
   count: 1
   location: "a pear tree"
 turtle-doves: two